-- Datos iniciales de ofertas y estados (respaldo 2026-10-08). Ejecutar después de schema.sql.
insert into public.ofertas (id,bloque,titulo,empresa,modalidad,salario,iso,url,enlace,nuevo,prio,archivado,motivo) values
('a1','admin','Responsable de Administración y Finanzas','Banco Comafi','Híbrido',null,null,'https://ar.indeed.com/q-administrativo-hibrido-l-buenos-aires,-buenos-aires-empleos.html','busqueda',false,null,false,null),
('a2','admin','Analista Funcional Senior, Administración y Finanzas','LA NACION','Híbrido',null,null,'https://ar.indeed.com/q-administrativo-hibrido-l-buenos-aires,-buenos-aires-empleos.html','busqueda',false,null,false,null),
('m1','ia','AI Automation Engineer (contrato): agentes sin supervisión, integraciones, pipelines en Python o Node','Blupax Pharmaceuticals','Remoto freelance (Sudamérica y Centroamérica)',null,'2026-10-01','https://www.getonbrd.com/empleos/programacion/ai-automation-engineer-contract-blupax-pharmaceuticals-remote',null,true,null,false,null),
('m2','ia','Desarrolladora/or Full Stack: plataforma SaaS B2B con IA, integración de LLM y APIs','Pallavicini Comunicación Directiva','Remoto freelance',null,'2026-10-03','https://www.getonbrd.com/jobs/programming/desarrolladora-pallavicini-comunicacion-directiva-remote',null,true,null,false,null),
('m5','ia','Desarrollador Full-Stack (Node.js, React, 4+ años)','Mediastream','Remoto (Argentina, Perú o México)','USD 2.200 a 2.500 por mes','2026-09-29','https://www.getonbrd.com/jobs/programacion/desarrollador-full-stack-mediastream-remote-f08c',null,true,null,true,'Exige título universitario en Computación o Ingeniería (verificado el 6/10)'),
('m6','ia','AI Engineer: IA generativa, agentes y RAG con Azure AI Foundry','Grupo Mariposa','Remoto (7 países, confirmar Argentina)',null,'2026-09-29','https://www.getonbrd.com/jobs/machine-learning-ai/ai-engineer-senior-grupo-mariposa-remote-be51',null,true,null,false,null),
('n8','ia','Full-Stack Developer React y Node.js (integración de IA o LLM, 5+ años)','Improving','Remoto (Argentina)',null,'2026-09-14','https://www.getonbrd.com/jobs/programming/fullstack-developer-react-node-js-improving-remote',null,false,null,false,null),
('n2','ia','Senior AI Engineer (agentes IA, MCP, Python/FastAPI)','Niuro','Remoto','USD 3.000 a 3.500 por mes','2026-09-24','https://www.getonbrd.com/jobs/machine-learning-ai/senior-ai-engineer-niuro-remote-803e',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('n3','ia','Web App Full-Stack Engineer (funciones con LLM)','Niuro','Remoto','USD 2.500 a 3.000 por mes','2026-09-24','https://www.getonbrd.com/jobs/programacion/web-app-full-stack-engineer-niuro-remote-4461',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('b1','ia','AI Agent Developer','Interfell','Remoto',null,null,'https://www.getonbrd.com/empleos/machine-learning-ai/ai-agent-developer-interfell-remote',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('b2','ia','Desarrollador(a) de Automatizaciones e IA','Jaiar Labs','Remoto',null,null,'https://www.getonbrd.com/empleos/programacion/desarrollador-a-de-automatizaciones-e-ia-jaiar-labs-remote',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('b3','ia','Ingeniero/a AI / Machine Learning (Semi Senior)','Lisit','Remoto',null,null,'https://www.getonbrd.com/jobs/machine-learning-ai/ingeniero-ai-machine-learning-lisit-remote',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('b4','ia','Ingeniero de IA/ML','Coderslab.io','Remoto',null,null,'https://www.getonbrd.com/jobs/programming/ingeniero-de-ia-ml-coderslab-io-remote',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('b5','ia','Automations Developer','Compara','Remoto',null,null,'https://www.getonbrd.com/empleos/programacion/automations-developer-compara-remote-2c5b',null,false,null,true,'Ya no figura entre los avisos vigentes (verificado el 5/10)'),
('r3','admin','Analista de Facturación (Administración)','Urbano Express Argentina','Híbrido',null,null,'https://ar.indeed.com/q-analista-de-facturaci%C3%B3n-y-cobranzas-l-buenos-aires,-buenos-aires-empleos.html','busqueda',true,3,false,null),
('r9','odoo','Analista Funcional para implementación de Odoo (3+ años)','Zivot, San Martín','A confirmar',null,null,'https://ar.computrabajo.com/trabajo-de-analista-funcional-odoo','busqueda',true,2,false,null),
('c2','odoo','Analista Funcional con experiencia en ODOO (Ref. 17831)','ADN Recursos Humanos','Remoto',null,null,'https://grabjobs.co/argentina/job/full-time/education-training/ref-17831-analista-funcional-con-experiencia-en-odoo-remoto-hiring-now-25306146',null,false,null,false,null);
insert into public.estados (job_id,status,archived,removed) values
('m1','pendiente',true,false),
('a1','postulado',true,false),
('a2','postulado',true,false),
('a3','descartado',true,true),
('a5','postulado',null,false),
('a6','postulado',null,false),
('a7','descartado',null,true),
('a8','postulado',null,false),
('a9','descartado',null,true),
('b2','postulado',null,false),
('b5','postulado',null,false),
('c1','descartado',true,true),
('c2','postulado',null,false),
('c3','descartado',null,true),
('c4','descartado',null,true),
('c5','postulado',null,false),
('c6','postulado',null,false),
('c7','postulado',null,false),
('m2','postulado',null,false),
('m3','descartado',true,true),
('m4','descartado',true,true),
('m6','postulado',null,false),
('n1','descartado',null,true),
('n10','descartado',null,true),
('n11','descartado',null,true),
('n12','descartado',null,true),
('n4','descartado',null,true),
('n5','descartado',null,true),
('n6','descartado',null,true),
('n7','descartado',null,true),
('n9','descartado',null,true),
('r1','descartado',true,true),
('r2','descartado',true,true),
('r3','postulado',true,false),
('r4','descartado',true,true),
('r5','descartado',true,true),
('r6','descartado',true,true),
('r7','descartado',true,true),
('r8','descartado',true,true),
('r9','postulado',null,false),
('s1','descartado',true,true),
('s2','descartado',true,true);